
AllCops:
  Include:
    - '*.gemspec'
    - Rakefile
    - Gemfile
    - Guardfile
  Exclude:
    - tmp/*
    - vendor/*

LineLength:
  Max: 100

MethodLength:
  Max: 17

WordArray:
  Enabled: false

RegexpLiteral:
  Enabled: false

AlignHash:
  # Alignment of entries using hash rocket as separator. Valid values are:
  #
  # key - left alignment of keys
  #   'a' => 2
  #   'bb' => 3
  # separator - alignment of hash rockets, keys are right aligned
  #    'a' => 2
  #   'bb' => 3
  # table - left alignment of keys, hash rockets, and values
  #   'a'  => 2
  #   'bb' => 3
  EnforcedHashRocketStyle: table
  # Alignment of entries using colon as separator. Valid values are:
  #
  # key - left alignment of keys
  #   a: 0
  #   bb: 1
  # separator - alignment of colons, keys are right aligned
  #    a: 0
  #   bb: 1
  # table - left alignment of keys and values
  #   a:  0
  #   bb: 1
  EnforcedColonStyle: separator

# TODO
Documentation:
  Enabled: false
